### ISSUE TITLE
Name collision with mrash afl-cov

### ISSUE THREAD

**Issue by richinseattle** [axt/afl-cov#1]
Hi, this tool looks amazing and I'm getting it setup to try out. I found it by accident due to a name collision with an already existing tool that many users of AFL are using: https://github.com/mrash/afl-cov

I thought I would point it out so you could consider your naming or possibly merge efforts. Keep up the cool work either way.

**Comment by axt** [comment]
Hi, sorry for my late answer. I've realized the name-clash after I've created the project. 

In its current stage, I wouldn't call it a tool, its just meant to be a simple example, to demonstrate the features of my other incubating state project https://github.com/axt/bingraphvis, which is a CFG visualizer pipeline for https://github.com/angr/angr/ generated CFGs. I'm not sure it is usable at all with real life apps, I've just used it with some smaller samples. It also has limitations, for example the "interactivity" is really simple (just some clickable SVGs), which suit my needs in my experimentations, but probably are a heavy limit in using it as a tool for real-life apps. I had some ideas how I could make it better, but unfortunatelly I didn't had time for it lately.

Anyway, have fun with it, just wanted to warn you about its limited scope :). 
Thanks for the feedback, I will consider renaming it.
